// GENERATED by scripts/scrape-products.mjs — do not edit by hand.
// Photo/price overrides scraped once at dev time; app stays offline (NFR-1).
export const scraped: Record<string, { image?: string; soloPriceKzt?: number }> = {
  "prd_01": {
    "image": "/products/prd_01.jpg"
  },
  "prd_02": {
    "image": "/products/prd_02.jpg"
  },
  "prd_03": {
    "image": "/products/prd_03.jpg"
  },
  "prd_04": {
    "image": "/products/prd_04.jpg"
  },
  "prd_05": {
    "image": "/products/prd_05.jpg"
  },
  "prd_06": {
    "image": "/products/prd_06.jpg"
  },
  "prd_07": {
    "image": "/products/prd_07.jpg"
  },
  "prd_08": {
    "image": "/products/prd_08.jpg"
  },
  "prd_09": {
    "image": "/products/prd_09.jpg"
  },
  "prd_10": {
    "image": "/products/prd_10.jpg"
  },
  "prd_11": {
    "image": "/products/prd_11.jpg"
  },
  "prd_12": {
    "image": "/products/prd_12.jpg"
  },
  "prd_13": {
    "image": "/products/prd_13.jpg"
  },
  "prd_14": {
    "image": "/products/prd_14.jpg"
  },
  "prd_15": {
    "image": "/products/prd_15.jpg"
  },
  "prd_16": {
    "image": "/products/prd_16.jpg"
  },
  "prd_17": {
    "image": "/products/prd_17.jpg"
  },
  "prd_18": {
    "image": "/products/prd_18.jpg"
  },
  "prd_19": {
    "image": "/products/prd_19.jpg"
  },
  "prd_20": {
    "image": "/products/prd_20.jpg"
  },
  "prd_21": {
    "image": "/products/prd_21.jpg"
  },
  "prd_22": {
    "image": "/products/prd_22.jpg"
  },
  "prd_23": {
    "image": "/products/prd_23.jpg"
  },
  "prd_24": {
    "image": "/products/prd_24.jpg"
  },
  "prd_25": {
    "image": "/products/prd_25.jpg"
  },
  "prd_26": {
    "image": "/products/prd_26.jpg"
  }
};
