// GENERATED by scripts/apply-scraped-items.mjs — do not edit by hand.
// Real marketplace items (exact URL, real price, listing photo) scraped at
// dev time via a real browser; the app stays offline at runtime (NFR-1).
export const scraped: Record<string, { image?: string; soloPriceKzt?: number; externalUrl?: string }> = {
  "prd_01": {
    "image": "/products/prd_01.webp",
    "soloPriceKzt": 13700,
    "externalUrl": "https://aliexpress.ru/item/1005010144068793.html"
  },
  "prd_02": {
    "image": "/products/prd_02.jpg",
    "soloPriceKzt": 34900,
    "externalUrl": "https://kaspi.kz/shop/p/smart-chasy-nolimit-gps-chernyi-137675544/"
  },
  "prd_03": {
    "image": "/products/prd_03.webp",
    "soloPriceKzt": 6000,
    "externalUrl": "https://aliexpress.ru/item/1005009562129736.html"
  },
  "prd_04": {
    "image": "/products/prd_04.jpg",
    "soloPriceKzt": 15712,
    "externalUrl": "https://ozon.kz/product/kolonka-portativnaya-2-v1-walker-kolonka-blyutuz-besprovodnaya-muzykalnaya-1849339996/"
  },
  "prd_05": {
    "image": "/products/prd_05.jpg",
    "soloPriceKzt": 385,
    "externalUrl": "https://kaspi.kz/shop/p/steklo-dlja-apple-iphone-15-117631465/"
  },
  "prd_06": {
    "image": "/products/prd_06.webp",
    "soloPriceKzt": 28000,
    "externalUrl": "https://www.wildberries.ru/catalog/1138372541/detail.aspx"
  },
  "prd_07": {
    "image": "/products/prd_07.jpg",
    "soloPriceKzt": 7989,
    "externalUrl": "https://kaspi.kz/shop/p/hudi-chernyi-148620407/"
  },
  "prd_08": {
    "image": "/products/prd_08.webp",
    "soloPriceKzt": 28300,
    "externalUrl": "https://www.wildberries.ru/catalog/299583782/detail.aspx"
  },
  "prd_09": {
    "image": "/products/prd_09.jpg",
    "soloPriceKzt": 15288,
    "externalUrl": "https://kaspi.kz/shop/p/ochki-solntsezaschitnye-poljarizatsionnye-modnye-prjamougol-nye-poljarizovannye-167170758/"
  },
  "prd_10": {
    "image": "/products/prd_10.jpg",
    "soloPriceKzt": 23336,
    "externalUrl": "https://ozon.kz/product/nabor-posudy-stolovoy-apollo-sky-16-predmetov-1641442229/"
  },
  "prd_11": {
    "image": "/products/prd_11.webp",
    "soloPriceKzt": 27500,
    "externalUrl": "https://www.wildberries.ru/catalog/172124668/detail.aspx"
  },
  "prd_12": {
    "image": "/products/prd_12.webp",
    "soloPriceKzt": 11200,
    "externalUrl": "https://aliexpress.ru/item/1005010675221324.html"
  },
  "prd_13": {
    "image": "/products/prd_13.jpg",
    "soloPriceKzt": 49912,
    "externalUrl": "https://ozon.kz/product/fen-stayler-s-ionizatsiey-tuvio-hbi1412-7-nasadok-sumka-dlya-hraneniya-temnyy-metallik-1664985713/"
  },
  "prd_14": {
    "image": "/products/prd_14.jpg",
    "soloPriceKzt": 1467,
    "externalUrl": "https://kaspi.kz/shop/p/real-techniques-nabor-kistei-dlja-makijazha-face-essentials-makeup-brush-set-5-110972122/"
  },
  "prd_15": {
    "image": "/products/prd_15.webp",
    "soloPriceKzt": 12800,
    "externalUrl": "https://www.wildberries.ru/catalog/1041634172/detail.aspx"
  },
  "prd_16": {
    "image": "/products/prd_16.webp",
    "soloPriceKzt": 25600,
    "externalUrl": "https://aliexpress.ru/item/1005008516177325.html"
  },
  "prd_17": {
    "image": "/products/prd_17.jpg",
    "soloPriceKzt": 19693,
    "externalUrl": "https://ozon.kz/product/samokat-trehkolesnyy-detskiy-rush-action-4490361985/"
  },
  "prd_18": {
    "image": "/products/prd_18.jpg",
    "soloPriceKzt": 2000,
    "externalUrl": "https://kaspi.kz/shop/p/interaktivnaja-igrushka-zhuchki-roboty-598-mul-tikolor-113237084/"
  },
  "prd_19": {
    "image": "/products/prd_19.jpg",
    "soloPriceKzt": 19927,
    "externalUrl": "https://ozon.kz/product/ganteli-razbornye-20kg-s-grifom-dlya-shtangi-2sht-10kg-1727862035/"
  },
  "prd_20": {
    "image": "/products/prd_20.webp",
    "soloPriceKzt": 4900,
    "externalUrl": "https://aliexpress.ru/item/1005005739486502.html"
  },
  "prd_21": {
    "image": "/products/prd_21.webp",
    "soloPriceKzt": 110900,
    "externalUrl": "https://www.wildberries.ru/catalog/187369345/detail.aspx"
  },
  "prd_22": {
    "image": "/products/prd_22.jpg",
    "soloPriceKzt": 20986,
    "externalUrl": "https://ozon.kz/product/blender-ctatsionarnyy-moshchnyy-s-izmelchitelem-4217438583/"
  },
  "prd_23": {
    "image": "/products/prd_23.jpg",
    "soloPriceKzt": 6990,
    "externalUrl": "https://kaspi.kz/shop/p/elektrochainik-elektricheskii-chainik-ek-01-chernyi-119851348/"
  },
  "prd_24": {
    "image": "/products/prd_24.webp",
    "soloPriceKzt": 34100,
    "externalUrl": "https://www.wildberries.ru/catalog/521535891/detail.aspx"
  },
  "prd_25": {
    "image": "/products/prd_25.webp",
    "soloPriceKzt": 93400,
    "externalUrl": "https://aliexpress.ru/item/1005010034185764.html"
  },
  "prd_26": {
    "image": "/products/prd_26.jpg",
    "soloPriceKzt": 5100,
    "externalUrl": "https://aliexpress.ru/item/1005008791693995.html"
  }
};
